BEGIN TRANSACTION;
DROP TABLE IF EXISTS "ITEM";
CREATE TABLE IF NOT EXISTS "ITEM" (
	"id"	INTEGER,
	"description"	VARCHAR,
	"price"	REAL,
	"SKUId"	INTEGER,
	"supplierId"	INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY("SKUId") REFERENCES "SKU"("id")
);
DROP TABLE IF EXISTS "SKUITEM";
CREATE TABLE IF NOT EXISTS "SKUITEM" (
	"RFID"	VARCHAR,
	"SKUId"	INTEGER,
	"Available"	INTEGER,
	"DateOfStock"	DATE,
	FOREIGN KEY("SKUId") REFERENCES "SKU"("id"),
	PRIMARY KEY("RFID")
);
DROP TABLE IF EXISTS "SKU";
CREATE TABLE IF NOT EXISTS "SKU" (
	"id"	INTEGER,
	"description"	VARCHAR,
	"weight"	REAL,
	"volume"	REAL,
	"notes"	VARCHAR,
	"position"	VARCHAR,
	"availablequantity"	INTEGER,
	"price"	REAL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "transportNote";
CREATE TABLE IF NOT EXISTS "transportNote" (
	"idTransportNote"	INTEGER,
	"deliveryDate"	DATE NOT NULL,
	"ROid"	INTEGER NOT NULL,
	FOREIGN KEY("ROid") REFERENCES "restockOrder"("id"),
	PRIMARY KEY("idTransportNote" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "restockTransactionItem";
CREATE TABLE IF NOT EXISTS "restockTransactionItem" (
	"quantity"	INTEGER NOT NULL DEFAULT 1,
	"idRestockOrder"	INTEGER NOT NULL,
	"idItem"	INTEGER NOT NULL,
	FOREIGN KEY("idRestockOrder") REFERENCES "restockOrder"("id") ON DELETE CASCADE
);
DROP TABLE IF EXISTS "restockOrder";
CREATE TABLE IF NOT EXISTS "restockOrder" (
	"id"	INTEGER,
	"issueDate"	DATE NOT NULL,
	"state"	TEXT NOT NULL,
	"supplierId"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "restockTransactionSKU";
CREATE TABLE IF NOT EXISTS "restockTransactionSKU" (
	"idRestockOrder"	INTEGER NOT NULL,
	"RFID"	INTEGER NOT NULL,
	FOREIGN KEY("idRestockOrder") REFERENCES "restockOrder"("id") ON DELETE CASCADE,
	FOREIGN KEY("RFID") REFERENCES "SKUITEM"("RFID") ON DELETE CASCADE
);
DROP TABLE IF EXISTS "testDescriptor";
CREATE TABLE IF NOT EXISTS "testDescriptor" (
	"idTestDescriptor"	INTEGER,
	"name"	TEXT NOT NULL,
	"procedureDescription"	TEXT,
	PRIMARY KEY("idTestDescriptor" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "SKUTestDescriptor";
CREATE TABLE IF NOT EXISTS "SKUTestDescriptor" (
	"idSKU"	INTEGER,
	"idTestDescriptor"	INTEGER,
	PRIMARY KEY("idSKU","idTestDescriptor"),
	FOREIGN KEY("idSKU") REFERENCES "SKU"("idSKU")
);
DROP TABLE IF EXISTS "testResult";
CREATE TABLE IF NOT EXISTS "testResult" (
	"idTestResult"	INTEGER,
	"date"	TEXT NOT NULL,
	"result"	INTEGER NOT NULL,
	"idTestDescriptor"	INTEGER,
	"RFID"	INTEGER,
	FOREIGN KEY("RFID") REFERENCES "SKUITEM"("RFID"),
	FOREIGN KEY("idTestDescriptor") REFERENCES "testDescriptor"("idTestDescriptor"),
	PRIMARY KEY("idTestResult" AUTOINCREMENT)
);
INSERT INTO "ITEM" VALUES (12,'a new sku',10.99,2,2);
INSERT INTO "ITEM" VALUES (13,'another new item',11.99,2,3);
INSERT INTO "SKUITEM" VALUES ('4567',2,1,'2022/05/04 18:49');
INSERT INTO "SKU" VALUES (2,'Edited sku',100.0,50.0,'first SKU','800234523412',50,10.99);
INSERT INTO "transportNote" VALUES (1,'2021/12/29',1);
INSERT INTO "restockOrder" VALUES (0,'2021/11/29 09:33','COMPLETEDRETURN',0);
INSERT INTO "restockOrder" VALUES (1,'2020/11/29 10:33','DELIVERED',0);
INSERT INTO "restockOrder" VALUES (2,'2021/11/29 09:33','ISSUED',1);
INSERT INTO "restockOrder" VALUES (3,'2021/11/29 09:33','ISSUED',1);
INSERT INTO "restockOrder" VALUES (4,'2021/11/29 09:33','ISSUED',1);
INSERT INTO "restockTransactionSKU" VALUES (0,4567);
INSERT INTO "testDescriptor" VALUES (1,'test1','qfqowij');
INSERT INTO "testResult" VALUES (1,'','false',1,4567);
COMMIT;
